theme: jekyll-theme-slate
title: LLM Gateway Documentation
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - "**/*.md"

# Make sure all markdown files are processed
permalink: pretty